<a href="https://colab.research.google.com/github/Gise08/Aprendizaje-Autom-tico/blob/main/AP_clase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importación de libreria
import numpy as np
# Ejercicio 1: Crear un array de 10 elementos con ceros.
ej_1 = np.zeros(10)
print("Ejercicio 1:", ej_1)

Ejercicio 1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Ejercicio 2: Genera un array con los números del 1 al 20.
ej_2 = np.arange(1, 21)
print("Ejercicio 2:", ej_2)

Ejercicio 2: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Ejercicio 3: Crea un array con los números pares del 2 al 50.
ej_3 = np.arange(2, 51, 2)
print("Ejercicio 3:", ej_3)

Ejercicio 3: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [ ]:
# Ejercicio 4:Matriz identidad de 3x3
ej_4 = np.eye(3)
print("Ejercicio 4 (Identidad):\n", ej_4)

Ejercicio 4 (Identidad):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.
ej_5 = np.random.rand(4, 4)
print("Ejercicio 5:\n", ej_5)

Ejercicio 5:
 [[0.74737746 0.48576557 0.04220631 0.80668603]
 [0.16651751 0.88958261 0.50764532 0.42468326]
 [0.88739788 0.36569962 0.26407596 0.46842796]
 [0.66447914 0.88083589 0.31944035 0.20793763]]


In [3]:
# Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ej_6 = a + b
print("Ejercicio 6:", ej_6)

Ejercicio 6: [5 7 9]


In [4]:
# Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.
m1 = np.random.randint(1, 11, (3, 3))
m2 = np.random.randint(1, 11, (3, 3))
ej_7 = np.dot(m1, m2) # O también m1 @ m2
print("Ejercicio 7 (Multiplicación matricial):\n", ej_7)

Ejercicio 7 (Multiplicación matricial):
 [[ 90  79 112]
 [ 72  58 100]
 [ 83  73 116]]


In [5]:
# Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100
# e imprime su máximo, mínimo y promedio.
ej_8 = np.random.randint(1, 101, 15)
print("Ejercicio 8:", ej_8)
print(f"Máximo: {ej_8.max()}, Mínimo: {ej_8.min()}, Promedio: {ej_8.mean()}")

Ejercicio 8: [46 60 89  3 39 71 75 81 56 61 38 83 61  7 20]
Máximo: 89, Mínimo: 3, Promedio: 52.666666666666664


In [6]:
# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.
matriz_5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_5x5)
print("Ejercicio 9 (Diagonal):", diagonal)

Ejercicio 9 (Diagonal): [ 1  7 13 19 25]


In [7]:
# Ejercicio 10: Dada una matriz 5x5 de enteros aleatorios entre 1 y 20,
# calcula la suma de cada fila y columna.
matriz_random = np.random.randint(1, 21, (5, 5))
suma_filas = np.sum(matriz_random, axis=1)
suma_columnas = np.sum(matriz_random, axis=0)
print("Ejercicio 10 (Matriz):\n", matriz_random)
print("Suma de filas:", suma_filas)
print("Suma de columnas:", suma_columnas)

Ejercicio 10 (Matriz):
 [[16  3  7 15  6]
 [15 20 13 17 15]
 [15 13 18 16  2]
 [20  5  4  6 13]
 [11 11  6 11 19]]
Suma de filas: [47 80 64 48 58]
Suma de columnas: [77 52 48 65 55]
